---
development:
  cloud_name: raheem
  api_key: '322818542123923'
  api_secret: QHXOwkXu5rIKWfzn9Rj0h2JZT98
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: raheem
  api_key: '322818542123923'
  api_secret: QHXOwkXu5rIKWfzn9Rj0h2JZT98
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: raheem
  api_key: '322818542123923'
  api_secret: QHXOwkXu5rIKWfzn9Rj0h2JZT98
  enhance_image_tag: true
  static_image_support: false
